node {
    // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "ArtifactoryServer"
    // Create an Artifactory Maven instance.
    def rtMaven = Artifactory.newMavenBuild()
    def buildInfo

    stage('Clone sources') {
        git url: 'https://github.com/jfrogdev/project-examples.git'
    }

    stage('Artifactory configuration') {
        // Tool name from Jenkins configuration
        rtMaven.tool = "maven-3.6.0"
        // Set Artifactory repositories for dependencies resolution and artifacts deployment.
        rtMaven.deployer releaseRepo:'maven-test-release', snapshotRepo:'maven-test-snapshot', server: server
        rtMaven.resolver releaseRepo:'maven-virtual-group', snapshotRepo:'maven-virtual-groupt', server: server
    }

    stage('Maven build') {
        buildInfo = rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install' 
    }

    stage('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}